### ISSUE TITLE
override "Loading..." on startup

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#22]
"src/ui/opengl/castlecontrolsimages.pas":
Loading := TGrayscaleAlphaImage.Create(LoadingWidth, LoadingHeight, LoadingDepth);
Move(LoadingPixels, Loading.RawPixels^, SizeOf(LoadingPixels));
Loading.URL := 'embedded-image:/Loading';
LoadingPixels points to "src/ui/opengl/castlecontrolsimages.image_data"

**Comment by michaliskambi** [comment]
To change the "Loading" image you want to change the `Theme.Images[tiLoading]` instance to something else.

This should usually be done in the `initialization` section of some unit (more specifically, it should happen before `Application.Run` is called and window is opened). As such, you cannot load image from disk at this moment (on Android, you cannot read from disk from `initialization` sections of units). So you want to process this image first with `image-to-pascal` tool (from CGE), to be an "embedded" image in a Pascal unit.

The general hints about adjusting the theme are here: https://castle-engine.sourceforge.io/manual_2d_user_interface.php#section_theme .

In summary, this is what you should do:

1. Run `image2pascal GameEmbeddedImages my_loading.png` (it will generate gameembeddedimages.pas unit)

2. Add a unit that does this:

```
unit GameAdjustLoadingScreen;

interface

uses CastleColors, CastleControls, GameEmbeddedImages;

implementation

initialization
  //Theme.LoadingBackgroundColor := Black; // adjust as needed
  //Theme.LoadingTextColor := White; // adjust as needed
  Theme.Images[tiLoading] := My_Loading;
  Theme.OwnsImages[tiLoading] := false;
end.
```

The `LoadingBackgroundColor` is used to fill the screen underneath the "loading" image. The reason we do this is because the loading image is scaled, but only proportionally, to fit the screen, so it's necessary to first fill the eventual space where the loading image would not be drawn.

So you usually want to adjust `LoadingBackgroundColor` --- to match your `my_loading.png` background.

The `LoadingTextColor` is a color used to scale the loading image components (just like TGLImage.Color scales the drawn image color). The name is somewhat misleading, it only makes sense when the "loading image" contains text. This is useful to adjust if you use the default loading image.

So you usually don't need to adjust `LoadingTextColor` if you're already customizing the `Theme.Images[tiLoading]` image.

I hope this helps :) I should document it better. For now, I'll link to this comment from https://castle-engine.sourceforge.io/manual_2d_user_interface.php#section_theme .

**Comment by eugeneloza** [comment]
Wow, thanks a lot!
I've just mentioned this issue in order not to forget to address it some time later :) Actually I've just wanted to make a separate "Loading..." text for different languages.
Now it looks much more simple, than I've expected.

**Comment by eugeneloza** [comment]
Works perfectly! Thanks!
