### ISSUE TITLE
CurrentRoutine in Log (FPC 3.1)

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#259]
In some time `{$I %CURRENTROUTINE%}` would be added in FPC (3.1+) as soon as it's implemented in stable version this would be a cute addition to `dLog`. Unfortunately it should be called from the core procedure, not from the `Log` routine.

**Comment by michaliskambi** [comment]
To get the name of the current procedure as a string, you could get the "backtrace". It requires being compiled with `-gl`, and it's not 100% reliable, but at least it works in any FPC version.

You could use it to get the name of the caller, or the caller's caller... so, unlike `{$I %CURRENTROUTINE%}`, it is useful on any level.

CGE has `DumpStackToString(Get_Frame)` (it's actually shown by CastleLog if you set BacktraceOnLog = true). It's actually a wrapper around `Dump_Stack` in FPC. You can look at `Dump_Stack` implementation in FPC (rtl/inc/system.inc, https://github.com/graemeg/freepascal/blob/master/rtl/inc/system.inc#L1217 ), it may be possible to remake it to get only the name of your caller as a string. It uses the global https://www.freepascal.org/docs-html/rtl/system/backtracestrfunc.html .

Maybe this will be helpful:)

**Comment by eugeneloza** [comment]
@michaliskambi thanks a lot!
Thou backtraces aren't really readable in most log-situations. Of course they provide more information, but actually, seeing a "Load3dSafe" in log is much more informative than "line 364 of DecoLoad" (which might be different for different versions of the game). And the version provided to users would hardly be compiled with `-gl` :)
At this point I just "hardcode" the procedure name into log message, and it's almost fine (unless I change something significantly and procedure gets renamed / changes owner) - basically that's the only case where `%CURRENTROUTINE%` would come handy.

P.S. I've looked at `BacktraceOnLog = true`, how do you think, maybe the output should be simplified/reparsed?
e.g. turn
>   ~~$00000000006DEA27 line 283 of ../src/base/castlelog.pas~~
>   $0000000000A8BE96 line 613 of src/decodungeongenerator.pas
>   $0000000000A9690E line 1316 of src/decodungeongenerator.pas
>   $0000000000A621E4 line 50 of src/decolevel.pas
>   $0000000000A62308 line 64 of src/decolevel.pas
>   $000000000045EE3E line 149 of src/decoherence.pas
>   $000000000045EED1 line 170 of src/decoherence.pas
>   $000000000045F0B0 line 209 of src/decoherence.pas
> ~~$0000000000494BCB line 4625 of ../src/window/castlewindow.pas~~

into

> src/decodungeongenerator(613<1316) < src/decolevel(50<64) < decoherence(149<170<209)

would prove much more "informative". If yes, I may do that (as an exercise :)) On the other hand it'll add significant amount of string-processing (which might be inappropriate for log).

**Comment by michaliskambi** [comment]
The string returned by `DumpStackToString` is generated by FPC `Dump_Stack`. I do not want to process it afterwards, this would be hacky (the format of `Dump_Stack` is not guaranteed, it's meant to be human-readable, not machine-readable).

My idea is that you could do something cleaner: you can look how `Dump_Stack` is implemented, and this should point to how you can get the current function name (or parent function name). Somewhere there _must_ be a logic that gets a pointer `Get_Frame` ( https://www.freepascal.org/docs-html/rtl/system/get_frame.html ), walks upwards along the call chain, and gets the function name as a string -- since this logic is used by the backtrace-printing utilities :)

Looking closer, you possibly could use GetLineInfo from LineInfo unit -- it returns a function name from an address (and other info, like source name and line number, which you can just ignore if you don't want to display it). See https://github.com/graemeg/freepascal/blob/master/rtl/inc/lineinfo.pp#L31

As for compiling with `-gl` -- it's not that crazy to compile with `-gl` for release :) This makes your executable larger, but I doubt it has any measurable effect on the code speed. You're not activating all the debug checks (like range or overflow checks, that may really slow down the code), you only add extra information to the executable.

**Comment by eugeneloza** [comment]
Sounds reasonable. I'll try to investigate this issue deeper. Thanks!

**Comment by eugeneloza** [comment]
Tried to get it right, but it looks inefficient, extremely overcomplicated and very platform-dependent. Still much easier for me to hardcode the functions names and wait until `%CURRENTROUTINE%` (compile-time) is in stable FPC version (or just switch to trunk).

**Comment by eugeneloza** [comment]
Almost persuaded myself to use FPCDeluxe and Lazarus+FPC trunk :)
