### ISSUE TITLE
[ERROR] no method in an ancestor class to be overridden: "GetChild:T3D;"

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#317]
Amend this to latest CGE version:
> decoactorbody.pas(80,14) Error: There is no method in an ancestor class to be overridden: "GetChild:T3D;"

**Comment by eugeneloza** [comment]
see here:
https://github.com/eugeneloza/castle-engine/commit/30ed30f63f0472688b677bbee017ab5e4c93376e#diff-34f1e691169e51c9bbb79b1b805dac77
https://github.com/eugeneloza/castle-engine/commit/74573970620b438d91016cf2ded1e280c39c2fb9#diff-34f1e691169e51c9bbb79b1b805dac77
https://github.com/eugeneloza/castle-engine/commit/4c113748b4e5a5ee07b3b133f05632ccd332e2a5#diff-34f1e691169e51c9bbb79b1b805dac77

**Comment by michaliskambi** [comment]
The GetChild method was indeed removed in CGE, in this commit: https://github.com/castle-engine/castle-engine/commit/74573970620b438d91016cf2ded1e280c39c2fb9 . The child added/removed this way was never 100% correct (as the code wasn't getting any notification when it changed, so it wasn't updating the World of the child). And it was causing a bit of complication in CGE code.

Sorry for the breakage. The fix is to use Add/Remove methods to add/remove the child.

The full solution to upgrade can be seen e.g. in the upgrade of `examples/resource_animations/resource_animations.lpr`, in https://github.com/castle-engine/castle-engine/commit/74573970620b438d91016cf2ded1e280c39c2fb9#diff-34f1e691169e51c9bbb79b1b805dac77 . I essentially 

1. move `TLoopAnimation.GetChild` to be a nested function inside `TLoopAnimation.Update`
2. add and call `procedure UpdateChild;` that simply calls the new (nested) `GetChild` every frame, and inserts/removes the child as it changes.

In general, the upgrade can be performed in many ways, but the above method (with `procedure UpdateChild;`) is probably the most straightforward.

**Comment by michaliskambi** [comment]
I'm preparing a pull request for the breakage I caused:)

**Comment by michaliskambi** [comment]
The fix for GetChild is ready, on https://github.com/michaliskambi/decoherence , but I'm working on more fixes --- I also removed `T3DOrient.Camera`, and I see that Decoherence was using it too... I'm thinking how to fix it best (and whether in CGE or Decoherence).

**Comment by michaliskambi** [comment]
I posted a fix for the GetChild problem in https://github.com/eugeneloza/decoherence/pull/318/files :)

Independently of this problem (GetChild), I also found another breakage that I caused in CGE -- I removed the T3DOrient.Camera property, and Decoherence was using it. I fixed this problem on the CGE side, so please make sure you use the latest CGE version, with this commit: https://github.com/castle-engine/castle-engine/commit/eea4ba10f81752cde625f51c5774898c7b57950a .

Decoherence compiles with CGE now:)

I'm sorry for the compatibility-breakage I caused...

**Comment by eugeneloza** [comment]
Thanks a lot! And no need to be sorry :)
