### ISSUE TITLE
Generics.Collections breaks down Lazarus IDE hints

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#329]
For some reason I can't use Lazarus IDE hints or other useful features such as ctrl+click in case Generics.Collections is used inside a unit. Very strange and inconvenient.

**Comment by eugeneloza** [comment]
This is the error shown in case I try to modify something in such units. As far as I remember it wasn't the case in Lazarus1.8RC4+FPC3.0.4.

> generics.collections.pas(81,27) Error: expected end., but TCustomArrayHelper found

![2017-11-25-223406_1366x768_scrot](https://user-images.githubusercontent.com/10726162/33234531-0d49031e-d231-11e7-9e54-fea3724b4138.png)

**Comment by eugeneloza** [comment]
Stop. It's Generics.Collections from FPC, not from Castle Game Engine (before it was CGE's version)... Hmmmm... that might be the issue...

**Comment by eugeneloza** [comment]
Made a topic here: http://forum.lazarus.freepascal.org/index.php?topic=39067.msg266895#msg266895

**Comment by michaliskambi** [comment]
Lazarus CodeTools simply cannot parse "Delphi mode" generics now, and Generics.Collections are using it. There are already bugreports about it:

    https://bugs.freepascal.org/view.php?id=32358
    https://bugs.freepascal.org/view.php?id=32291
    https://bugs.freepascal.org/view.php?id=30271
    https://bugs.freepascal.org/view.php?id=32291
    https://bugs.freepascal.org/view.php?id=30227

I did not yet found a way to workaround it myself. We just have to wait until it's fixed in Lazarus CodeTools. Very unfortunate, but I have no better solution.

The CGE code can use generics in "ObjFpc mode" (almost always, except the "FPC 3.0.x + CastleUtils unit" is a special combination, see https://github.com/castle-engine/castle-engine/commit/7377ddd8169aba9d194ba9cb07786834e5eb4a9d ). But it cannot help the issue of using Generics.Collections in your own applications.

**Comment by eugeneloza** [comment]
Ah, I see. Not too much problem. Thanks a lot!
So, closing this issue as nothing can yet be done.
