### ISSUE TITLE
Shouldn't be LogStream freed in the end?

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#358]
I create a log stream in DecoLog
````
LogStream := TFileStream.Create(NiceDate + '.log', fmCreate);
````
Use it to output the log, but actually never free it. Seems invalid, added a "Free" procedure, thou I'm uncertain, maybe it's automatically managed by Log? I should investigate it more closely, it might cause memory leaks and even bugs in a very unexpected place.

**Comment by eugeneloza** [comment]
Well, there's no SIGSEGV on LogStream.Free. That means this was a correct guess :)

**Comment by michaliskambi** [comment]
Passing your own stream instance to `CastleLog.InitializeLog` indeed does not make it automatically freed, so you should free it yourself:)

General comments:

1. When the documentation in CGE does not explicitly say anything, then by default we _"do not take responsibility"_ for freeing the given object instance. When we _"take responsibility"_, I tried to always mention it explicitly at the docs of given method/property, saying something like _"the object instance given here becomes owned by this..."_ or _"do not free the given instance yourself anymore, it becomes owned..."_ or by explicitly taking a boolean parameter like `OwnsSomething`.

2. Warning: It is not 100% safe to assume that if `Xxx.Free` succeeded then it's valid:) Sometimes freeing an already-freed object may go on without errors, because of pure "luck" / accident, but it's still an error (it may crash in other circumstances). Of course it's a reasonable test, I'm just warning to not trust it 100% -- compiler does not guarantee that freeing an already-freed object will be clearly signaled as an error. Even if it's usually reliable when compiling in debug mode and with `-gh`. In any case, it's best to look at the docs and/or source code:)

Happy holidays!:)

**Comment by eugeneloza** [comment]
Yeah, thanks a lot!
That what I was thinking of, but I've just got too used to loading objects in SceneManager automatically frees them afterwards :) So got a bit confused on that :)
The problem was that I write log to file only in Release mode, and Release mode didn't have `-gh` on, so I had to test it manually.
And Merry Christmas to you too!
This year we have a holiday on 25th December too (earlier years we had only 7th January as a Christmas holiday :))
