### ISSUE TITLE
Autodetect and reuse X3D Nodes (at least Appearance)

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#398]
> Use texture atlases (try to reuse the whole X3D `Appearance` across many X3D shapes, if possible). This avoids texture switching when rendering

as suggested here https://castle-engine.io/manual_optimization.php#section_textures
(this requires remaking blender loading, but worth it, I guess). Maybe there is a way to automatically say if the two X3D nodes are equal without actually comparing all of its fields (e.g. by hash)? Anyway, even if it goes this way, it'll be only run-once procedure, so won't slow things down significantly.

I wonder if it's possible to automatically reuse `IndexedFaceSet` and, maybe, some others too. Move it to a new "later" issue when this one is closed.

**Comment by eugeneloza** [comment]
The more I think about adding hashes to `X3DNode`s, the more I like the idea. It can even be added as TCastleScene or TCastleSceneManager feature to autodetect and autoreuse the nodes (if allowed by the user, of course - identical nodes may still be made different later) as many non-placeholder objects in Blender are likely to be created as copies (e.g. trees).

**Comment by michaliskambi** [comment]
The point of the advice "try to reuse the whole X3D Appearance across many X3D shapes, if possible" is mainly to use one texture, and one material, for multiple shapes. You do not actually need to have the `Appearance` node reused in order to benefit from this optimization, our engine is smarter than this. You do not need to go out of your way to have equal TAppearanceNode reference.

In Blender, just use a single material for a couple of shapes (reusing the Blender material makes the underlying X3D Material reused as well). Although even without this, the engine will be able to reuse GPU shaders for multiple different materials.

And for texture atlases, use Blender's ability to bake textures into one big texture.

You usually do not need to change anything in the code of the engine, or code of your game, to benefit from this optimization advice:)

**Comment by eugeneloza** [comment]
> reusing the Blender material makes the underlying X3D Material reused as well

Thanks a lot! That's exactly what I was worried about :)
I think the memory used can still be reduced by making duplicate X3D nodes into pointers, but it's hardly worth it. At least not as a priority task.
So, this concludes the issue :D Thanks!
