### ISSUE TITLE
Window no 3D render

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#73]
When in other than travel mode 3D world render should be disabled (to save FPS). Not 100% sure about it, but looks like a good idea. However, I couldn't find anywhere how to stop TCastleWindow from calling render on each update. Maybe #72 will fix this issue?

**Comment by michaliskambi** [comment]
You can set AutoRedisplay = false, https://castle-engine.sourceforge.io/apidoc/html/CastleControl.TCastleControlCustom.html#AutoRedisplay , and then the window is not rendered all the time. It is rendered only when you call Invalidate (or when you set AutoRedisplay back to true, of course), or when operating system requested it (e.g. because the user moved/resized the window, or obscured it by another window and then unobscured).

Note that this disables rendering *everything*, i.e. the window will just not redraw (unless you call Invalidate etc.). If you really want to disable only 3D rendering, then you can just hide the scene manager(s) that do your 3D rendering, e.g.  by SceneManager.Exists := false.

**Comment by eugeneloza** [comment]
Thanks a lot! SceneManager.Exists := false is exactly what I was looking for!
